language: node_js
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.16.1
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=msoese/legal-aid-finder
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
node_js:
  - '7'
services:
  - docker
script:
  - docker-compose pull
  - docker-compose build
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr create-repository --repository-name $REPO --region us-west-2
  - eval $(aws ecr get-login --region us-west-2)
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BUILD_NUMBER
  - docker-compose push $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BUILD_NUMBER
  #- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'