language: node_js
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
node_js:
  - '7'
services:
  - mongodb
  - docker
script:
  - npm install
after_success:
  #- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'