language: node_js
sudo: required
dist: trusty
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=msoese/legal-aid-finder
node_js:
  - '7'
before_install:
  #
script:
  - npm test
after_success:
  #
