language: node_js
sudo: required
dist: trusty
env:
  global:
    - COMMIT=${TRAVIS_COMMIT::8}
    - REPO=msoese/legal-aid-finder
node_js:
  - '7'
before_install:
  - npm start
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
addons:
  chrome: stable
before_script:
  #
script:
  - sudo docker build -t legal-aid-finder -t $REPO:$TRAVIS_BUILD_NUMBER -f Dockerfile .
  - npm test
  - nightwatch -e chrome
  # - sudo docker-compose pull
  # - sudo docker-compose build --no-cache
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr create-repository --repository-name $REPO --region us-west-2
  - eval $(aws ecr get-login --region us-west-2)
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BUILD_NUMBER
  - docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BUILD_NUMBER
  # - docker-compose push $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BUILD_NUMBER
  #- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'
