language: node_js
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
node_js:
  - latest
  - '6.3'
services:
  - mongodb
  - docker
script:
  - npm test
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'