language: node_js
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=msoese/legal-aid-finder
before_install:
  #
node_js:
  - '7'
services:
  - docker
script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "bh/dev" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker-compose build -t legal-aid-finder -t $REPO:$TRAVIS_BUILD_NUMBER
after_success:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - aws ecr create-repository --repository-name $REPO --region us-west-2
  - eval $(aws ecr get-login --region us-west-2)
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BUILD_NUMBER
  - docker push $AWS_ACCOUNT_NUMBER.dkr.ecr.us-west-2.amazonaws.com/$REPO:$TRAVIS_BUILD_NUMBER
  #- './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'