version: '3.3'

services:

  laf-prod:
    container_name: laf-prod
    build:
      context: .
      dockerfile: Dockerfile-prod
    volumes:
      - '.:/usr/src/app'
    ports:
      - '3000:3000'
      - '3001:3001'
    environment:
      - NODE_ENV=production
